export const GET_ACCOUNT_INFO_REQUEST = 'GET_ACCOUNT_INFO_REQUEST';
export const GET_ACCOUNT_INFO_SUCCESS = 'GET_ACCOUNT_INFO_SUCCESS';
export const GET_ACCOUNT_INFO_FAILURE = 'GET_ACCOUNT_INFO_FAILURE';

export const LOGIN_SUBMIT_REQUEST = 'LOGIN_SUBMIT_REQUEST';
export const LOGIN_SUBMIT_SUCCESS = 'LOGIN_SUBMIT_SUCCESS';
export const LOGIN_SUBMIT_FAILURE = 'LOGIN_SUBMIT_FAILURE';

export const LOGOUT_SUBMIT_REQUEST = 'LOGOUT_SUBMIT_REQUEST';
export const LOGOUT_SUBMIT_SUCCESS = 'LOGOUT_SUBMIT_SUCCESS';
export const LOGOUT_SUBMIT_FAILURE = 'LOGOUT_SUBMIT_FAILURE';

export const REGISTER_SUBMIT_REQUEST = 'REGISTER_SUBMIT_REQUEST';
export const REGISTER_SUBMIT_SUCCESS = 'REGISTER_SUBMIT_SUCCESS';
export const REGISTER_SUBMIT_FAILURE = 'REGISTER_SUBMIT_FAILURE';

export const SET_ACCOUNT_INFO_REQUEST = 'SET_ACCOUNT_INFO_REQUEST';
export const SET_ACCOUNT_INFO_SUCCESS = 'SET_ACCOUNT_INFO_SUCCESS';
export const SET_ACCOUNT_INFO_FAILURE = 'SET_ACCOUNT_INFO_FAILURE';

export const CHANGE_ACCOUNT_INFO_REQUEST = 'CHANGE_ACCOUNT_INFO_REQUEST';
export const CHANGE_ACCOUNT_INFO_SUCCESS = 'CHANGE_ACCOUNT_INFO_SUCCESS';
export const CHANGE_ACCOUNT_INFO_FAILURE = 'CHANGE_ACCOUNT_INFO_FAILURE';